### ISSUE TITLE
SVG Sprite - how to use

### ISSUE THREAD

**Issue by travisricks** [mbarker84/eleventy-parcel#4]
Hi Michelle,

First of all, this repository is great. Thank you so much for taking the time to put it together!

I was wondering if there is any documentation on how to use the SVG sprite feature? 

Thank you in advance.

**Comment by edheltzel** [comment]
@travisricks If you checkout the `package.json` 
you'll see `"svg": "svg-sprite-generate -d src/icons -o src/_includes/partials/sprite.svg"` 

which is using [frexy/svg-sprite-generator](https://github.com/frexy/svg-sprite-generator) - if you read up on that repo all the info you need will be there. 

```shell
Usage: svg-sprite-generate [options]

Options:
  -V, --version               output the version number
  -c --csv <csv>              CSV file path
  -d --directory <directory>  SVG folder
  -l --list <list>            List of files
  -o --output <output>        Out put to file
  -s --sprite <sprite>        Another sprite file
  -h, --help                  output usage information
````
